name: Compile Minecraft Spigot or Paper (BuildTools)
description: Makes it easier to compile multiple Spigot/Paper versions at the same time and speed up clean builds
author: Christian Koop

branding:
  icon: arrow-down-circle
  color: orange

inputs:
  versions:
    required: false
    default: latest
    description: Versions to build (sperate multiple with ',')
  generateSrc:
    required: false
    default: 'false'
    description: Should sources be generated?
  remapped:
    required: false
    default: 'false'
    description: Should use the SpecialSource Plugin of md_5 to deobfuscate Mojang-NMS-Packets
  generateDoc:
    required: false
    default: 'false'
    description: Should the documentation be generated?
  disableJavaCheck:
    required: false
    default: 'false'
    description: Should we disable the BuildTools's Java-Version-Check
  forceRun:
    required: false
    default: 'false'
    description: Disables the check for existing files in the local maven repository
  threads:
    required: false
    default: '-1'
    description: The amount of builds allowed to run at a time, set to '-1' to use system's cpu count
  buildToolProvider:
    required: false
    default: SpigotMC
    description: Whose BuildTool should be used? (SpigotMC [default], SpraxDev)

runs:
  using: node12
  main: dist/index.js
